language: r
r:
  - devel
  - oldrel
  - release


latex: false
fortran: false
pandoc: false

warnings_are_errors: true
sudo: required

services:
  - docker
  
r_binary_packages:
  - fs

r_github_packages:
  - AntonelliLab/outsider.base
  - jimhester/covr

after_success:
- Rscript -e 'covr::coveralls()'

addons:
  apt:
    packages:
      - libapparmor-dev
      - libssh-dev
      - r-cran-ape

notifications:
  email:
    on_success: change
    on_failure: always
