language: r
latex: false
fortran: false
pandoc: false

warnings_are_errors: true
sudo: required

services:
  - docker
  
r_github_packages:
  - jimhester/covr

after_success:
- Rscript -e 'covr::coveralls()'

addons:
  apt:
    packages:
      - libapparmor-dev

notifications:
  email:
    on_success: change
    on_failure: always

